### ISSUE TITLE
Temperature and humidity stoped showing up after replacing sensor

### ISSUE THREAD

**Issue by piotrmocko** [trekawek/air-quality-info#104]
I had BME280 temperature, humidity, and pressure sensor. Lately, it started reporting a negative temperature of -143. I have replaced it with DHT22 sensor. Now, valid data are sent by the device. But they don't show up on the page

Data received by aqi.eco

![image](https://user-images.githubusercontent.com/977916/213169955-7490170a-096e-4bd8-a188-1735be934494.png)

```
{
  "esp8266id": "4011675",
  "software_version": "NRZ-2020-133",
  "sensordatavalues": [
    {
      "value_type": "SDS_P1",
      "value": "44.88"
    },
    {
      "value_type": "SDS_P2",
      "value": "25.17"
    },
    {
      "value_type": "temperature",
      "value": "3.20"
    },
    {
      "value_type": "humidity",
      "value": "99.90"
    },
    {
      "value_type": "samples",
      "value": "4964080"
    },
    {
      "value_type": "min_micro",
      "value": "28"
    },
    {
      "value_type": "max_micro",
      "value": "20070"
    },
    {
      "value_type": "interval",
      "value": "145000"
    },
    {
      "value_type": "signal",
      "value": "-70"
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/977916/213171005-475e4550-120f-4925-bc4d-e91c888665f8.png)

**Comment by trekawek** [comment]
DHT22 is normally used in the Nettigo Air Monitor to measure the temperature of the heater. That's why it's visible under heater_temperature in the visible data.

You can change the device configuration to use this field as the main temperature, by adding a custom field mapping:

* JSON field: temperature
* Database field: temperature

<img width="559" alt="Screenshot 2023-01-19 at 09 35 40" src="https://user-images.githubusercontent.com/142138/213393479-26fcd364-75a1-4b49-a163-7a428ca67612.png">

**Comment by piotrmocko** [comment]
Thanks, it works
